# Site wide configuration

title: "Matti Ojala"
description: If you're here to find out who is Matti Ojala, you came to the right place! Find out more about my background, career and hobbies in electronics, microcontrollers, automation, softwares and web. Enjoy!
logo: logo.jpg # TODO! 120x120 px default image used for Twitter summary card
# teaser: teaser_home.jpg # TODO! 400x250 px default teaser image used in image archive grid
locale: fi
url:
baseurl:
feed:
  path: atom.xml
fawesome: fa-home
version: 2.1.0
image: teaser_home.jpg

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
# permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Site owner
owner:
  name:
  email:
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


picture:
  path:
  source: "/assets/images/_fullsize"
  output: "generated"
  suppress_warnings: false

plugins:
  - jekyll-picture-tag

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
